NUXT/layouts/default.vue
NUXT/nuxt.config.js
NUXT/pages/settings.vue

https://user-images.githubusercontent.com/31113245/155630878-2075255d-1811-4146-a1b5-13dd8c7bbac2.mov

amoled theme

---

NUXT/layouts/default.vue
NUXT/pages/mods/theme.vue

Kind of a hacky fix, but should work for now

Fix for issue #46

---

NUXT/layouts/default.vue

This should work, checked on emulator.

Fix for issue #93

---

NUXT/layouts/default.vue

Should fix the problem for now, but could discuss if a pop up that alerts the user to an empty input is needed. If not this should be fine.

Fix for issue #100

---

NUXT/pages/home.vue
NUXT/plugins/innertube.js
NUXT/plugins/youtube.js
NUXT/static/constants.js

Note that there is a small bug regarding some thumbnails not loading, though I'm not exactly sure how that will be tackled yet.

Refactored Recommendation API formatting to be more stable

---

NUXT/layouts/default.vue

Sorry the previous fix was invalid after more testing, this should work.

Additional fix for issue #100

---

NUXT/pages/watch.vue

For some reasons, no preview because the CI build for android has failed (no more apk) :(
So basically the changes is to make numbers more readable by adding comma. (example: from `12345` to `12,345`)

Added comma into numbers.

---

NUXT/pages/mods/about.vue

Please do confirm it fixes the issue, explanation of solution provided in issue #116, alternative fix also discussed there.

Proposed fix for issue #116

---

NUXT/layouts/default.vue
NUXT/package.json

light theme fix

---

NUXT/layouts/default.vue

😬 im dumb please forgive me

---

NUXT/components/bottomNavigation.vue
NUXT/components/topNavigation.vue
NUXT/layouts/default.vue
NUXT/nuxt.config.js
NUXT/pages/index.vue
NUXT/pages/mods/theme.vue
NUXT/pages/search.vue
NUXT/pages/watch.vue
ios/App/Podfile

(screenshots look chunky because I have my phone's font set to Largest Extra Bold)

Search & Watch UI improvements

---

NUXT/components/VideoRenderers/compactVideoRenderer.vue
NUXT/components/VideoRenderers/gridVideoRenderer.vue
android/app/src/main/assets/capacitor.config.json

Recommended videos and Search:
- Improved landscape browsing experience by collapsing thumbnail image and showing text to its right
[Image](https://photos.app.goo.gl/PozSWa8Z4Xgtnwqp8) of this change.

Shrink thumbnails and shift text in landscape video list

---

NUXT/components/UtilRenderers/slimVideoDescriptionRenderer.vue

There were a few bugs in the previous release, most notably with how links are handled. They have been fixed now

fix: in app-browser of description links

---

NUXT/components/CompactRenderers/compactChannelRenderer.vue
NUXT/components/CompactRenderers/compactVideoRenderer.vue
NUXT/components/UtilRenderers/slimVideoDescriptionRenderer.vue
NUXT/components/gridRenderers/gridVideoRenderer.vue
NUXT/pages/mods/theme.vue
NUXT/plugins/renderers.js
NUXT/plugins/youtube.js

Removed that one reference to Roblox
unified how links are handled

Chore: Small fixes

---

NUXT/components/UtilRenderers/slimVideoDescriptionRenderer.vue

Fixed issue where description wouldn't appear when clicked by removing "this" from template section
Also added some margin to the bottom to separate description from recommended videos

Fixed description not appearing

---

NUXT/pages/mods/plugins.vue

[****Yousef seal of approval****]

plugin card ui

---

readme.md

Uh I messed it up last time and its been bothering me since

Readjusted headers weights

---

NUXT/components/CompactRenderers/compactVideoRenderer.vue
NUXT/components/UtilRenderers/baseVideoRenderer.vue
NUXT/components/gridRenderers/gridVideoRenderer.vue
NUXT/components/gridRenderers/videoWithContextRenderer.vue

Created a new Utility Renderer named baseVideoRenderer - all graphical rendering should now go here and all data should be passed via props.
Changed already existing video renderers to use this new base renderer

Refactored Video selection rendering to be more consistent

---

NUXT/components/Player/index.vue

Set up system to enter/exit fullscreen based on rotation. 
Also, when manually triggering fullscreen on vertical videos, it will now enter a vertical fullscreen player.
Technical details: Since the JavaScript Fullscreen API only works with a button trigger, I have changed the fullscreen strategy so it just makes the video player container full-height instead. The status/navigation bars are still hidden as normal. Some additional logic was required to differentiate between handling a fullscreen button press (which locks the rotation) and physically rotating the device (which doesn't).
[Video](https://photos.app.goo.gl/H9QWcmMENCKujvKp9) (note: screencapture doesn't allow device rotation mid-recording, so only showing using the manual fullscreen button here)

Enter fullscreen on device rotation, vertical fullscreen mode

---

NUXT/components/Player/index.vue

Doubletap -> Double tap

---

NUXT/pages/watch.vue

allows you to "download" by opening the video in VLC video player
also casting workaround for now 👍

open in vlc (downloading)

---

NUXT/plugins/languages/spanish.js

Basic translation of the app in Spanish 😎

App in Spanish (sorry for flooding with pull requests)

---

NUXT/plugins/languages/chinese-traditional.js

I had some trouble with linting but it's fixed now

Translate app into Chinese (Traditional)

---

NUXT/plugins/languages/spanish.js

Update Spanish translation with new fields

Update Spanish app

---

NUXT/plugins/language.js

Add Macedonian language pack

---

NUXT/plugins/languages/macedonian.js

bruh forgor to add the file 💀

---

readme.es.md
readme.he.md
readme.ja.md
readme.md
readme.ms.md
readme.nl.md
readme.ta.md
readme.zh-hans.md
readme.zh-hant.md

Remove unnecessary badges from all readme.md s

---

NUXT/plugins/languages/brazilian-portuguese.js

Adds Brazilian Portuguese translation.

feat: add pt-br translation file

---

readme.es.md
readme.fr.md
readme.he.md
readme.id.md
readme.ja.md
readme.md
readme.mk.md
readme.ms.md
readme.nl.md
readme.pt-br.md
readme.ta.md
readme.zh-hans.md
readme.zh-hant.md

736subscribers subscribers no more

Telegram Badge Fix

---

NUXT/plugins/language.js
NUXT/plugins/languages/bulgarian.js
NUXT/plugins/languages/macedonian.js
readme.mk.md

- Add bulgarian translation by samihamchev
- Fix Macedonian typos

did translations stuff

---

NUXT/plugins/languages/polish.js

Update of Polish translation of the application

Update polish.js translation

---

NUXT/plugins/languages/french-fr.js

I fixed a few typos and added some words that would be more appropriate for French (France).

Update and rename french.js to french-fr.js, create a separate french-ca.js version if necessary.

---

NUXT/plugins/languages/readme.md

- Google Translate or other automatic translations are not allowed
- Some words can remain in English (ej: Dislike)
- Where name of the language should be translated and where not
- A little explanation of how fields work
- How to do a pull request
If you disagree with something feel free to make any changes you want.

Add translations guide (an Readme file in Language folder explaining how to translate)

---

NUXT/plugins/languages/readme.md

Thanks 404-Program-not-found for your advice

Mistakes corrected on Translations Guide

---

readme.es.md

VueTube Readme in 16 languages, that’s globalization

Add RYD acknowledgement in Spanish Readme

---

NUXT/plugins/languages/spanish.js

Que le dice una vaca a otra vaca?
Muuuu
Que esperabas es una vaca xd

Update spanish app with new fields

---

NUXT/plugins/languages/dutch.js

Updated the dutch.js file to support the new lines of text

Updated dutch.js

---

NUXT/plugins/languages/chinese-simplified.js
NUXT/plugins/languages/chinese-traditional.js

also includes new dark mode tagline!

Update in-app Chinese translations

---

NUXT/layouts/default.vue
NUXT/plugins/utils.js

Added result variable declaration and included handling m.youtube.com in regex

fix issues with external URL handling

---

NUXT/plugins/languages/tamil.js

Add tamil.js

---

readme.es.md
readme.md

The change just applies to English and Spanish readmes.

Add SponsorBlock to features and links to RYD and SponsorBlock websites in Readme

---

readme.zh-hans.md
readme.zh-hant.md

- remove "s" from "Dislikes"
- change term for "information" in Traditional Chinese

Update readme Chinese translations

---

NUXT/plaginlər/dillər/azerbaijan.js
NUXT/plugins/languages/azerbaijan.js

I have added an Azerbaijani translation and I am sure that my translations are correct.

Update azerbaijan.js language

---

readme.zh-hans.md
readme.zh-hant.md

- Add translate app line in "How to Contribute" section
- change terms for "click here" and "contribute code" in Traditional Chinese
- Add missing "Why am I doing this?" section to Traditional Chinese (also capitalized D in Discord)

Update Chinese readmes

---

NUXT/plugins/languages/polish.js

New strings translated + some minor fixes to the existing translation yet again! 😋

Polish Update v3

---

readme.md

Added Donate section to Readme

---

NUXT/plugins/language.js
NUXT/plugins/languages/korean.js

add korean translation

---

NUXT/plugins/languages/korean.js
readme.kr.md
readme.md

add korean readme

---

readme.es.md

Added donate section in Spanish Readme

Donations in Spanish 

---

readme.kr.md

It's hard to make the original feel come alive.
Sorry, i guess this is my limit.

korean translate thought-for-thought

---

readme.es.md

- Added English original Readme contributors
- Translated "Official" and "Maintainer" terms

Spanish Readme Improvements

---

NUXT/plugins/languages/spanish.js

New field added to Spanish.js translation file

New field to Spanish App

---

NUXT/plugins/languages/russian.js

Add Russian Translation

---

NUXT/plugins/languages/indonesian.js

Translating missing Indonesian words & fixing small amount of Indonesian grammar

Indonesian translation update

---

readme.es.md

No matter how badly fingerprints are damaged, they will always grow back in their original pattern

Update readme in Spanish

---

readme/readme.ms.md

This might conflict with pr from @nokanol45

Big update to Malay Readme

---

readme.md

Added a collapsable progress section with all the info of the Discord #progress section.

Another non-app related pull request for the devs 😀👍

---

readme/readme.zh-hans.md
readme/readme.zh-hant.md

Also changed 顯示 to 查看 in readme contributor for consistency.
Side question: should we use some kind of webhook (or some unified system) for the progress section? that way we can update the progress section of all the readmes easily.

Add progress section in Chinese readmes

---

NUXT/nuxt.config.js
NUXT/pages/activities/install.vue

API selector

---

NUXT/plugins/languages/german.js

I changed some translations according to the guidelines and added missing ones.

Added and fixed german translations

---

NUXT/plugins/languages/polish.js

Additional newer strings translated, minor fixes and improvements to correct translation.

Polish translation update V4 Dominik😎😁

---

NUXT/plugins/languages/italian.js.bak
readme/readme.it.md
readme/readme.it.md.bak

Fixed grammar for italian.js
install: "Ultimo" > Correct translation for "install" in italian is "installa". I don't know why it says "Ultimo" here.
Ultimo means "last" in italian.
enjoy: "Ci auguriamo **che avrai** un'esperienza straordinaria" > It's not correct in italian language.

Grammar fix for italian.js and Update readme.it.md

---

readme.md

I made it a little more natural to read and added some information. Also the "¿Why am I doing this?" section was completely reworked.
Also, you should enable Discuss and Wiki sections in the Github repository in my opinion. Discuss would help people to discuss about the future of VueTube, and in the Wiki I could add some detailed information about the app.

Readme Performed and detailed (please merge before GD 2.2 releases)

---

NUXT/plugins/languages/spanish.js

Changed some things and added the new updates section

Update Spanish Translation

---

NUXT/plugins/languages/romanian.js

I made few changes to sync with english.js

Updated Romanian translation

---

readme.md

Fixed a misspelling in the english readme

Added missing letter in English Readme

---

NUXT/plugins/languages/indonesian.js

Translating missing Indonesian words & fixing small amount of Indonesian grammar

Indonesian translation update part 2

---

NUXT/plugins/languages/indonesian.js

Translating missing Indonesian words

Indonesian translation update part 3

---

NUXT/plugins/languages/french-fr.js

- Added new translations that were missing 
- Changed a few translations to make them more natural
- Updated the "Bravo Six" quote to make it faithful to the official French translation for the original quote

French Translation update

---

NUXT/pages/mods/theme.vue

Make "Custom" text appear translated in Theme section

Intense change

---

NUXT/plugins/languages/indonesian.js

Small fix about Indonesian translation

---

NUXT/plugins/language.js
NUXT/plugins/languages/hungarian.js

Just added hungarian.js, and added it into language.js

Adding Hungarian language

---

NUXT/plugins/languages/polish.js

Polish Update, minor fixes.😎❤️ Dominik

---

NUXT/plugins/languages/polish.js

Translated Update component, very minor fixes.

Fully translated New Updates component. 😎 Dominik

---

NUXT/plugins/languages/serbian.js

Added serbian.js

---

readme/readme.id.md

I updated and fixed the typo of [README for Indonesian](https://github.com/VueTubeApp/VueTube/blob/main/readme/readme.id.md).

Update Indonesian readme.id.md

---

NUXT/plugins/language.js
NUXT/plugins/languages/english.js
NUXT/plugins/languages/hindi.js
NUXT/plugins/languages/marathi.js

Although the Hindi file shows a lot of changes its just Prettier code alignment changes. Same goes for English.
**Waiting for verification from one of the following tagged below as I am doubtful about usage of a few words in the Marathi file.**

Added Marathi language, updated Hindi to the match English

---

NUXT/plugins/languages/hungarian.js
readme/readme.hu.md

Changed the Hun Readme, The app hun version

Updated the Hungarian Translates

---

readme.md
readme/readme.zh-hans.md
readme/readme.zh-hant.md

- typo and grammar corrections in English readme
- update Chinese readmes (except for "why are we doing this?" section and ending tag line - too corny imo)

Update Chinese, English readmes

---

NUXT/plugins/languages/korean.js

Korean translation update

---

readme.md
readme/readme.ua.md

This PR adds a Ukrainian translation of the Readme.md file.

Add Ukrainian readme translation

---

readme/readme.tr.md

Fix images not showing.
Fix some places that haven't translated.

Update Turkish Readme Translation

---

NUXT/plugins/languages/japanese.js

We avoid translations that are unclear or unnatural for some functions.

add japanese.js and translate

---

NUXT/plugins/language.js
NUXT/plugins/languages/japanese.js

I forgot to add Japanese to languages.js, so I added it

Add Japanese

---

NUXT/plugins/languages/azerbaijan.js

An existing file has been updated.

azerbaijan.js updated.

---

NUXT/plugins/languages/malayalam.js

Translated the app to Malayalam language.

created malayalam.js

---

NUXT/plugins/languages/azerbaijan.js

azerbaijan.js

---

NUXT/plugins/languages/english.js

english.js

---

readme.md
readme/readme.ms.md

VueTube app releases link was outdated so I updated it to the latest releases

Updated VueTube Canary app link in readme

---

NUXT/components/historyCard.vue
NUXT/pages/history.vue
NUXT/pages/library.vue
NUXT/pages/watch.vue
NUXT/store/history/index.js

Implemented a feature where the video viewed by the user is tracked on local storage and can be viewed locally in the library section of the app. I have included the screenshots of the changes below.

feat: added local history

---

.github/workflows/node.js.yml
NUXT/components/Player/index.vue
NUXT/pages/home.vue
NUXT/pages/mods/updates.vue
NUXT/plugins/constants.js
NUXT/plugins/innertube.js
NUXT/plugins/languages/ukrainian.js
android/app/src/main/AndroidManifest.xml

1. Changed YouTube api when loading video
2. Fixed displaying of information about new update (Size, created_at, download_count etc.)
3. Fixed double >> in Android Manifest.
Minor changed:
1. Updated ukrainian language (added few strings to properly displaying text in app)
2. Trying fix console errors spam

Fixed player loading, fixed layout with new updates

---

NUXT/components/Comments/authorCommentBadgeRenderer.vue
NUXT/components/Player/index.vue
NUXT/components/Playlist/playlistCard.vue
NUXT/components/Playlist/playlistVideoCard.vue
NUXT/components/UtilRenderers/YtTextFormatterNew.vue
NUXT/components/historyCard.vue
NUXT/plugins/innertube.js
NUXT/plugins/renderers.js
NUXT/plugins/youtube.js
NUXT/store/channel/index.js

1. [Changed checking of metadata.icon value in iconTypeMap](https://github.com/VueTubeApp/VueTube/commit/1954f44802c3d885a2ae4bd66afb2082609d095e)
2. Changed video preview quality from maxresdefault to hqresdefault
3. [Added new type of channel url - /@examplechannel](https://github.com/VueTubeApp/VueTube/commit/90931d728649fb226e83cf3d6d13d09fb47d589d)
4. [Fixed displaying channels which opened from search.](https://github.com/VueTubeApp/VueTube/commit/1fdf1510a60cb437e45919d5faa454b6f7efd92c)
5. [Fixing some bugs in displaying description.](https://github.com/VueTubeApp/VueTube/commit/b16cfb7fa5884f49fac83bd92357ee38ad0e3144)
6. [Created function makeDecipherFunction for deciphering url`s. Fixed an issue where the application would stop working if the function was generated incorrectly. …

Major update

---

.github/dependabot.yml

Hi, when I build the project recently I saw that there are some outdated dependencies.
It might be good to automatically update dependencies. I would suggest using dependabot. 
Dependabot is a service of github. It will check the versions of the npm packages and  create automatic pull requests to update them. 
I think that it still needs to be enabled by the maintainers under Settings->Security->Code security and analysis:
For more information, checkout this page: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
If this pr gets accepted I would also create an pr to add dependabot to the extractor repo.

Dependabot - Dependency management

---

NUXT/plugins/innertube.js

Fixed errors when app can`t start - https://github.com/VueTubeApp/VueTube/issues/653#issue-1745749783
ATTENTION - this does not fix slow video download speed

fix(innertube): Fixed decipher function

---

readme.md

This Pull Request fixes a typographical error in the README.md file.
- Corrected "avaiable" to "available" in the README.md file.
This fix is not related to any existing issue. It's a minor typo that I noticed while reviewing the README.
Thank you for considering this contribution.

doc(README): remove typo

---

NUXT/plugins/innertube.js

https://github.com/VueTubeApp/VueTube/issues/623

Fixed low speed of playing video

---

NUXT/plugins/innertube.js

Fix for variables with $ symbol

fix(innertube): Fixed low speed of playing video
